# Generated by Django 3.0.1 on 2019-12-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_info',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='stock_info',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
