# Generated by Django 3.0.1 on 2019-12-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20191229_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=6)),
                ('company_name', models.CharField(max_length=15)),
                ('news_title', models.TextField(null=True)),
                ('news_date', models.DateTimeField()),
            ],
        ),
    ]
